name: Compiling_only_main

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      -  main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
                     
    - name: compile code if cpp
      run: g++ -o out.exe HelloWorld.cpp || true 

    - name: compile code if cpp
      run: gcc -o out.exe HelloWorld.c || true
          
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: out.exe
        path: out.exe
        
    - name: check compiled file
      run: file artifacts/out.exe
