name: Compiling_only_main

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      -  main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks the github repo
      uses: actions/checkout@v2
                     
    - name: compiles code if cpp
      run: g++ -o out.exe HelloWorld.cpp || true 

    - name: compiles code if c
      run: gcc -o out.exe HelloWorld.c || true
          
    - name: Uploads executable
      uses: actions/upload-artifact@v2
      with:
        name: out.exe
        path: out.exe
        
    - name: checks compiled file
      run: file out.exe
