name: Cross compile c/cpp code CI

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      -  main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: install Arm cross compiler
      run:  sudo apt-get update

    - name: install Arm cross compiler
      run: sudo apt-get install --reinstall build-essential

    - name: install Arm cross compiler
      run: sudo apt install --yes {gcc,binutils}-arm-linux-gnueabihf 
           
    - name: files in directory
      run: ls
      
    - name: compile code
      run: arm-linux-gnueabihf-gcc -o out.exe HelloWorld.cpp
          
    - name: dir for atrifacts
      run: mkdir -p artifacts

    - name: mov .exe to folder
      run: mv out artifacts/out

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: artifacts/out
        
    - name: check compiled file
      run: file artifacts/out.exe
