name: Cross compile c/cpp code CI

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

   
    - name: install Arm cross compiler
      run: apt install --yes {gcc,binutils}-arm-linux-gnueabihf

    
    - name: compile code
      run: arm-linux-gnueabihf-gcc -o out.exe HelloWorld.cpp

   
    - name: check compiled file
      run: file out.exe
